In [12]:
import geopandas

In [ ]:
# without using parquet, read_file() takes ~6 min
# the geojson file is 617 MB
nyc_trees = geopandas.read_file("data/2015 Street Tree Census - Tree Data.geojson")

In [14]:
# takes < 1 min with parquet
# note: you need to install pyarrow for this to work
nyc_trees = geopandas.read_parquet("data/nyc_trees.parquet")

### Warning: 
* The GeoPandas documentation states that to_parquet is not reliable for production unless you are ok with rewriting the parquet file after updates
* The reason being that they are using an early version of GeoParquet and future updates could introduce breaking changes

### WKB
* Any geometry columns present are serialized to WKB format in the file.
* Well-Known Binary format
* each geometry object is encoded as a series of bytes
* only supports simple geometries like points, lines and polygons
* another related encoding is WKT (Well-Known Text)

### Parquet
* apache file format
* column oriented 
* allows for better compression, and thus faster reads

In [ ]:
nyc_trees.to_parquet('data/nyc_trees.parquet')

In [15]:
nyc_trees.head()

,nta,health,zipcode,latitude,nta_name,state,trnk_wire,y_sp,brnch_othe,root_grate,...,address,sidewalk,root_other,created_at,borocode,block_id,trnk_light,tree_dbh,root_stone,geometry
0,QN17,Fair,11375,40.72309177,Forest Hills,New York,No,202756.768749,No,No,...,108-005 70 AVENUE,NoDamage,No,08/27/2015,4,348711,No,3,No,POINT (-73.84422 40.72309)
1,QN49,Fair,11357,40.79411067,Whitestone,New York,No,228644.837379,No,No,...,147-074 7 AVENUE,Damage,No,09/03/2015,4,315986,No,21,Yes,POINT (-73.81868 40.79411)
2,BK90,Good,11211,40.71758074,East Williamsburg,New York,No,200716.891267,No,No,...,390 MORGAN AVENUE,Damage,No,09/05/2015,3,218365,No,3,No,POINT (-73.93661 40.71758)
3,BK90,Good,11211,40.71353749,East Williamsburg,New York,No,199244.253136,No,No,...,1027 GRAND STREET,Damage,No,09/05/2015,3,217969,No,10,Yes,POINT (-73.93446 40.71354)
4,BK37,Good,11215,40.66677776,Park Slope-Gowanus,New York,No,182202.425999,No,No,...,603 6 STREET,Damage,No,08/30/2015,3,223043,No,21,Yes,POINT (-73.97598 40.66678)

In [16]:
nyc_trees.geometry

0         POINT (-73.84422 40.72309)
1         POINT (-73.81868 40.79411)
2         POINT (-73.93661 40.71758)
3         POINT (-73.93446 40.71354)
4         POINT (-73.97598 40.66678)
                     ...
683783    POINT (-73.95494 40.71321)
683784    POINT (-73.85665 40.71519)
683785    POINT (-74.13652 40.62076)
683786    POINT (-73.90311 40.85083)
683787    POINT (-73.78753 40.73217)
Name: geometry, Length: 683788, dtype: geometry